### ISSUE TITLE
Feature: ignore changes in files like README.md?

### ISSUE THREAD

**Issue by johanneskastl** [helm/chart-testing#530]
**Is this a request for help?**: No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I am using the helm-chart-testing action, that uses the chart-testing tool (obviously :-) ). It complains, if I make small changes to e.g. a chart's README.md file, and do not bump the chart's version.

For things like README.md or similar it would be nice, if those files could be ignored by `ct list-changed`.

I found no commandline argument that would allow me to do that. I also found no hint if this is possible using the config file.

**Comment by mavimo** [comment]
@johanneskastl I was thinking the same and I'll like to take care of the implementation of this feature.

Considering that:
 - Helm charts support `.helmignore` in order to not include files in the chart
 - The current implementation of `ct` do not take it into account, this mean that in case of files that are not part of the package (e.g.: file in `ci` folder) every change in those file require a chart bump, also if at the end the chart artefact do not change (same for test folder or any other file/folder that is not shipped in the chart).
 - `README.md` is not an asset that impact the chart functionality, I'm not sure if it should be part of the chart itself or should be omitted from the tarball (but we should keep in the repo) using the `.helmignore` file.

I have a few option in mind:
 - Add the functionality to take `.helmignore` into consideration during the chart-change evaluation (excluding files that are ignored from `.helmignore` [here](https://github.com/helm/chart-testing/blob/main/pkg/chart/chart.go#L709). Helm ignore functionality is available [here](https://github.com/helm/helm/tree/952708b436bb2c8d5ef0e2e9ef1d8aabe64aeae9/internal/ignore) but since is an internal package we can't depend from it and we need to mirror the functionality)
 - Add a functionality that omit files from CLI flag/configuration (eg `.ctignore` file or `--ignore-files` flag), this seems a bit risky since we can omit files that are part of the final artefact potentially exposing chart developer to issues

Do you have any opinion on that?

**Comment by johanneskastl** [comment]
@mavimo Your first proposal sounds good, nice to see there is already a PR for that.

On a related note, I found that people exclude things in the Github Action definition:
```
---
name: "Charts: Lint and test"

on:
  pull_request:
    paths:
      - 'charts/**'
      - '!charts/**/README.md'
      - '!charts/**/README.md.gotmpl'
```

([untested example](https://github.com/nicholaswilde/helm-charts/blob/main/.github/workflows/charts-lint-test.yaml))

**Comment by mavimo** [comment]
@johanneskastl as I understand it going to stop the pipeline to work if only the readme file is changed, this is not bad but then we need to have a dedicate pipeline only for the version check (plus we need to report all the files & folder to ignore also in the CI pipeline, that might be a bit redundant and counterintuitive for a person working on the chart)

**Comment by alessio-perugini** [comment]
Having this feature would be great! @cpanato, when you'll be free, would you consider (#411)? 🤓
