### ISSUE TITLE
Support for pushing charts to a helm chart repo

### ISSUE THREAD

**Issue by yatzek** [helm/chart-testing#6]
Would be nice to have a script allowing to push charts to a helm chart repo. I would also suggest not to include the ci folder with *-values.yaml files in the published chart. There can be some sensitive data that should not be published.

**Comment by mattfarina** [comment]
I was starting to think about how we could handle this. Consider the following different cases:

1. Push the chart to chartmuseum
1. Push the chart to object storage (handling all the major cloud providers APIs)
1. Push a chart to a repo using GitHub pages
1. So many more...

There are a lot of permutations to this.

Since this is a testing image.... wouldn't it make more sense for pushing to be a separate step in the CI toolchain using a different image/process. Once that could be tailored to the tool being pushed to?

**Comment by rimusz** [comment]
I think we can close this issue
